os:
    - linux
    - osx

language: php

php:
    - 5.6
    - 5.5
    - 5.4

services: redis-server

env:
    - APP_INCLUDE=tests/TestWorker.php QUEUE="foo[4],bar[4],test[4],foobar[4]"
    # Use YAML file and test cron jobs
    - CRON=1

before_script:
    - composer install --no-interaction --dev
    - if [[ "$CRON" == 1 ]]; then cp randr.yaml.example randr.yaml ; else rm -rf randr.yaml ; fi

script:
    - "sh -c 'bin/randr' > randr.pid"
    - bin/spam
    - bin/spam-delayed
    - if [[ "$CRON" == 1 ]]; then sleep 60; test -f cron.output; fi

after_script:
   - bin/killall
