language: php

php:
    - 5.6
    - 5.5
    - 5.4

services: redis-server

env:
    - APP_INCLUDE=tests/TestWorker.php QUEUE="foo[4],bar[4],test[4],foobar[4]"

before_script:
    - composer install --no-interaction --dev

script:
    - "sh -c 'bin/randr' > randr.pid"
    - bin/spam

after_script:
   - bin/killall

#notifications:
#  email: false
#  irc:
#    channels:
#      - "irc.freenode.org#phpunit"
#    use_notice: true
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/6668f52f3dd4e3f81960
#    on_success: always
#    on_failure: always
#    on_start: false
